# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az bicep build --file main.bicep
      az bicep build --file niab-azure-prereqs.bicep

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment sub create --name Bicep --template-file main.bicep -l uksouth'
